---
name: terraform validate
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  validate:
    name: terraform validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
      options: --entrypoint /bin/sh

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: terraform validate
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform init
          terraform validate